[build]
  # Build command to run before deploying
  command = "npm run build"
  # Directory to publish to Netlify after build (default is public)
  publish = "public"

[functions]
  # Directory where serverless functions are located
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
